#!/usr/bin/env node
/**
 * Writes public/robots.txt and public/sitemap.xml from VITE_SITE_URL.
 *
 * Those two files live in public/ and are copied as-is, so Vite's `%VITE_*%`
 * substitution — which index.html uses — cannot reach them. Generating them keeps
 * one source of truth: a fork edits VITE_SITE_URL in .env and everything follows.
 *
 * `npm run build` runs this first, so a deploy can never ship a sitemap pointing
 * at somebody else's domain.
 */

import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');

// Same precedence Vite uses: real env wins, then .env.
function readSiteUrl() {
  if (process.env.VITE_SITE_URL) return process.env.VITE_SITE_URL;
  const envFile = path.join(root, '.env');
  if (fs.existsSync(envFile)) {
    const match = fs.readFileSync(envFile, 'utf8').match(/^\s*VITE_SITE_URL\s*=\s*(.+)\s*$/m);
    if (match) return match[1].trim().replace(/^["']|["']$/g, '');
  }
  return '';
}

const raw = readSiteUrl();
if (!raw) {
  process.stderr.write('VITE_SITE_URL is not set — skipping robots.txt and sitemap.xml\n');
  process.exit(0);
}

// A trailing slash matters: every other URL is built by appending to this.
const site = raw.endsWith('/') ? raw : `${raw}/`;
const today = new Date().toISOString().slice(0, 10);

fs.writeFileSync(
  path.join(root, 'public/robots.txt'),
  `# Generated by scripts/build-seo.mjs — edit VITE_SITE_URL in .env instead.
User-agent: *
Allow: /

Sitemap: ${site}sitemap.xml
`
);

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by scripts/build-seo.mjs — edit VITE_SITE_URL in .env instead. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  '  <url>',
  `    <loc>${site}</loc>`,
  `    <lastmod>${today}</lastmod>`,
  '    <changefreq>weekly</changefreq>',
  '    <priority>1.0</priority>',
  '  </url>',
  '</urlset>',
  '',
].join('\n');

fs.writeFileSync(path.join(root, 'public/sitemap.xml'), sitemap);

process.stderr.write(`wrote public/robots.txt and public/sitemap.xml for ${site}\n`);
